# Generated by Django 5.0.1 on 2024-11-22 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_education_user_alter_experience_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="personelprofile",
            name="department_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Department"
            ),
        ),
        migrations.AddField(
            model_name="personelprofile",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Is Approved"),
        ),
        migrations.AddField(
            model_name="personelprofile",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Is Manager"),
        ),
        migrations.AddField(
            model_name="personelprofile",
            name="is_on_leave",
            field=models.BooleanField(default=False, verbose_name="Is On Leave"),
        ),
        migrations.AddField(
            model_name="personelprofile",
            name="leave_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Leave End Date"
            ),
        ),
        migrations.AddField(
            model_name="personelprofile",
            name="leave_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Leave Start Date"
            ),
        ),
        migrations.AddField(
            model_name="personelprofile",
            name="manager_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Manager Title"
            ),
        ),
        migrations.AddField(
            model_name="personelprofile",
            name="responsibilities",
            field=models.TextField(
                blank=True, null=True, verbose_name="Responsibilities"
            ),
        ),
        migrations.AlterField(
            model_name="baseprofile",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="core.baseprofile",
            ),
        ),
        migrations.DeleteModel(
            name="TeamProfile",
        ),
    ]
