# Generated by Django 5.0.1 on 2024-11-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_attendance_leave_worklog_workreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leave",
            old_name="user",
            new_name="employee",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="leave_type",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="total_days",
        ),
        migrations.AddField(
            model_name="leave",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
