# Generated by Django 5.0.1 on 2024-11-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_user_leave_employee_remove_leave_is_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Is Approved"),
        ),
    ]
